CREATE TABLE instruments
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    code        VARCHAR(255),
    exchange    VARCHAR(255),
    description VARCHAR(255),
    expiration  date,
    type        SMALLINT,
    CONSTRAINT pk_instruments PRIMARY KEY (id)
);