spring:
  application:
    name: algotrading-app
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

ql:
  connections:
    - name: quik
      host: localhost
      port: 1250